# IT a docker-compose file for start all palladium services.
version: '3'
services:
  nginx-server:
    image: nginx:latest
    volumes:
      - apidata:/palladium/api
      - ./dist/:/palladium/view/
      # For local compose uncomment volume below and comment `./palladium-ssl.conf`
      # - "./palladium.conf:/etc/nginx/conf.d/default.conf"
      - "./palladium-ssl.conf:/etc/nginx/conf.d/default.conf"
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    tty: true
    restart: always
  api-server:
    build:
      context: https://github.com/palladium-tms/palladium-api.git
    restart: always
    depends_on:
      - db
    volumes:
      - apidata:/palladium-api/tmp/puma/socket/
    tty: true
    environment:
      RACK_ENV: "production"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
  db:
    image: postgres
    shm_size: 1gb
    restart: always
    volumes:
        - db:/var/lib/postgresql/data
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
  clientside-build:
    build:
      context: https://github.com/palladium-tms/palladium-view.git
    volumes:
      - ./dist/:/palladium-view/host_dist
volumes:
  db:
  apidata: {}
