# IT a docker-compose file for start all palladium services.
version: '3'
services:
  nginx-server:
    image: nginx:1.16.0
    volumes:
      - apidata:/palladium/api
      - ./dist/:/palladium/view/
      - ./palladium.conf/:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    tty: true
  api-server:
    build:
      context: https://github.com/flaminestone/palladium-api.git
    command: ["bundle", "exec", "puma -C config/puma.rb"]
    depends_on:
      - db
    volumes:
      - apidata:/palladium-api/tmp/puma/socket/
    tty: true
    environment:
      - RACK_ENV=production
      - JWT_SECRET=
      - JWT_ISSUER=
  db:
    image: postgres
    volumes:
        - db:/var/lib/postgresql/data
  clientside-build:
    build:
      context: https://github.com/flaminestone/palladium-view.git
    volumes:
      - ./dist/:/palladium-view/host_dist
volumes:
  db:
  apidata: {}
